name: awsome_tools
description: This package contains some useful tools for flutter development.
version: 1.0.0
homepage:

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  another_flushbar: ^1.12.30

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: